### ISSUE TITLE
Get Lat/Lng individual?

### ISSUE THREAD

**Issue by distantnative** [lekkerduidelijk/kirby-geolocation-field#1]
Any way to get the latitude or longitude individually?
Would be a great way, if one could do $page->location()->lat()

**Comment by juangiga** [comment]
The map does not appear in my template. Using Kirby 2.1.0. I have followed all the steps and do not to make this worked.

**Comment by tasinttttttt** [comment]
Hey @juangiga the plugin only stores the geolocation data. It's up to you to generate a map (using mapbox or google maps for example) and add the geolocation.

You can look at the `geolocation.js` file in the `assets/js` plugin folder for an example of how to generate a google map with the marker.

**Comment by lekkerduidelijk** [comment]
Hi @juangiga, please create a new issue if your problem still persists.
