### ISSUE TITLE
Wrong id of location field.

### ISSUE THREAD

**Issue by tickHub** [lekkerduidelijk/kirby-geolocation-field#2]
In geolocation.js you refer to the location field as <code>locationField: $("#form-field-location")</code>

But i think it should be <code>locationField: $("#form-field-coordinates")</code>

**Comment by lekkerduidelijk** [comment]
Thanks for reporting. I will investigate this.

**Comment by tickHub** [comment]
Ah! The field name is dynamic (specified in the blueprint file), so it can be everything of course.
You can fix it for now with <code>locationField: $("[type=geolocation]"),</code> as long if you facilitate only one instance per page.

**Comment by lekkerduidelijk** [comment]
@tickHub I was unaware that the field `type` in the blueprint is set as the `<input type='geolocation'>` in the panel directly. I thought it was only needed to activate the custom field.

It looks like this:
```html
<input class="input input-is-readonly" type="geolocation" name="location" autocomplete="on" placeholder="Coordinates" readonly="" id="form-field-location" tabindex="-1" data-field="location">
```

When changing the field name to 'location2' it looks like this:
```html
<input class="input input-is-readonly" type="geolocation" name="location2" autocomplete="on" placeholder="Coordinates" readonly="" id="form-field-location2" tabindex="-1" data-field="location">
```

Selecting an input on an 'invalid' type attribute doesn't feel like the way to go. I would rather stick with the `id` of the field and instruct people to use `location` as the field name in their blueprint. I will update the readme.

But please feel free to issue a PR if you have a solid solution for this. Maybe loop through all the input fields with `data-field="location"` to allow multiple instances?
