### ISSUE TITLE
Map not showing up in wrapper when using within Structure tabs

### ISSUE THREAD

**Issue by DavidUnzue** [lekkerduidelijk/kirby-geolocation-field#4]
When using the Geolocation field within tabs in a structure field modal box (see [structure tabs plugin](https://github.com/ian-cox/Kirby-Structure-Tabs.git)), if the location field is in any tab but the first one, the gmap loads but isn't showing up in the wrapper. After resizing the browser window, the gmap shows up.

![geolocation](https://cloud.githubusercontent.com/assets/9588510/10363341/4f59806e-6db4-11e5-9e79-6e456fef8246.gif)

**Comment by lekkerduidelijk** [comment]
I see what you mean. I've not tested this in a structure pop up. 
I think the load event is not properly triggered. I'll get back to you.

**Comment by lekkerduidelijk** [comment]
I've investigated this for a bit. It seems Google Maps doesn't load the tiles if it is loaded inside of a hidden div. To work around this you can force a resize event on the map.

*Current code - line [52-54](https://github.com/ian-cox/Kirby-Structure-Tabs/blob/master/assets/js/structuretab.js#L52)*
```
        $("#" + tab_id).find('input.structuretab').prop('checked', true);
        $("#" + tab_id).siblings().find('input.structuretab').prop('checked', false);
      });
```

*New code*
```
        $("#" + tab_id).find('input.structuretab').prop('checked', true);
        $("#" + tab_id).siblings().find('input.structuretab').prop('checked', false);

        // Force resize to show tiles
        google.maps.event.trigger(map, 'resize');
      });
```

Please let me know if this works for you. Best option here would be if @ian-cox added events to the tab switch I could hook into.

**Comment by DavidUnzue** [comment]
Your fix is working partially, now the map is showing up, but the default Long. and Lat. aren't being centered anymore.

**Comment by lekkerduidelijk** [comment]
Are the previously stored coordinates being centered when you edit an entry?
You should be able to get the centering working by writing some javascript near the location I pointed out above.

As I pointed out, this feels more like a compatibility issue with that plugin than a 'bug' in my plugin.
