### ISSUE TITLE
Feature Request: Please Allow Multiple Instances Per Page

### ISSUE THREAD

**Issue by luxlogica** [lekkerduidelijk/kirby-geolocation-field#5]
I need to have 2 location fields in the same template. Is there a workaround for this? - tried Googling and checking in the Kirby forum, but have not come across anything...

**Comment by lekkerduidelijk** [comment]
What kind of errors do you get? Currently the field is linked on 'id' and not on 'class' or data attribute. 
You could try to change that in the PHP brick build code and loop through a collection of elements in JavaScript.

**Comment by luxlogica** [comment]
My programming skills do not go that far - sorry... :-(

**Comment by puckey** [comment]
( This is fixed in our fork amongst other things: https://github.com/studiomoniker/kirby-geolocation-field/commit/6aab3133c61a0c547c2c3253b84813e4b6577f8b )

**Comment by lekkerduidelijk** [comment]
@puckey Nice job! Looks good.

**Comment by luxlogica** [comment]
@lekkerduidelijk, will the improvements made by @puckey be pulled into this repo?

**Comment by puckey** [comment]
I reverted a few layout changes I made, so it looks more like the original and created a pull request: https://github.com/lekkerduidelijk/kirby-geolocation-field/pull/7
