### ISSUE TITLE
Feature Request: Add Map Output on Frontend via a PHP Function

### ISSUE THREAD

**Issue by luxlogica** [lekkerduidelijk/kirby-geolocation-field#6]
The geolocation field allows us to capture a geolocation on the backend. That is great, but it's just the first part of the equation. What is needed now if for us to be able to use this geolocation to output a map on the frontend. Ideally, it would be great to be able to do something like this this on a template...:

```php
<?php echo $page->location()->toMap();?>
```

...and have it automatically output a GoogleMap iFrame, or alternatively a map created using **[Leaflet](http://leafletjs.com/)**, which would be even better (as it's open source, and does not require an API key)!

**Comment by lekkerduidelijk** [comment]
I think implementations differ too much to write one generic output method for this. 
This plugin was developed originally to put multiple product vendor locations on a single map. It was used in a loop which created multiple markers for one map. 
Also to optimize for performance most of the times I build the Google Maps script tag with JavaScript to prevent it from loading on all pages.

Feel free to create a PR for this and I will look into it.

**Comment by luxlogica** [comment]
The most common use-case is the client wanting to show 1 address on 1 map - usually on a Contact page or section. Use cases such as multiple markers on a single map are the exception. Being able to cover even the simplest use case would already be extremely useful for a large number of folks.

**Comment by lekkerduidelijk** [comment]
Using this plugin for a simple 'Contact page or section' is overkill. Company addresses don't change that often imo.

**Comment by luxlogica** [comment]
You are assuming that this plugin is being used by web *programmers*, who will feel comfortable dynamically inserting a javascript map on a page. I believe many Kirby users are primarily web *designers*, who are not necessarily savvy with coding. It's much easier for these customers to add a single line of PHP to their template, which uses info from their Kirby template, which they already know how to do...

**Comment by lekkerduidelijk** [comment]
I think Kirby users are more developers than designers. Most designers that I know 'build' websites with something like WordPress or SquareSpace.

I can understand where you are coming from, but this is my point of view (and my plugin :smile:). This plugin requires some coding knowledge and is build around Google's ecosystem (GeoCoder and Maps).
That's what it is. 

Again feel free to fork or PR.
