### ISSUE TITLE
Plugin not working anymore after June 22

### ISSUE THREAD

**Issue by maximiliankiepe** [lekkerduidelijk/kirby-geolocation-field#9]
Hello,

the plugin does not work anymore. I think it is because of the updates from 22. June (https://developers.google.com/maps/pricing-and-plans/standard-plan-2016-update). Tried to put my key in the google maps script in the loadGmap function but it does not seem to work.

Any suggestions?

Thx for the great plugin, worked perfectly...

**Comment by lekkerduidelijk** [comment]
Any errors in your console? What part isn't working?

**Comment by CodeStalker** [comment]
Im seeing this issue as well. First time i loaded it, i got a bunch of errors that were related to having an ad blocked enabled (the one built into Opera browser). Once i turned that off, the plugin will not load due to missing API Key. Gave this error....

Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys

**Comment by CodeStalker** [comment]
Looks like you need a valid API key and to pass it on the script call like so:

<script async defer src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap"
  type="text/javascript"></script>

**Comment by maximiliankiepe** [comment]
First it was the API Key missing. But when i put the API Key in like this:
https://maps.googleapis.com/maps/api/js?key=AIzaSyBuRIIAJn1ilXtI7fkuCvqJRtgOjt6&callback=initMap

the error warning is:
"js?v=2.2.3:129 GET https://maps.googleapis.com/maps/api/js?key=AIzaSyBuRIIAJn1ilXtI7fkuCvqJRtgOjt6N&callback=initMapcallback=Geolocation.build"

when i erase init Map callback ( https://maps.googleapis.com/maps/api/js?key=AIzaSyBuRIIAJn1ilXtI7fkuCvqJRtgOjt6 ) I get this error:
"js?key=AIzaSyBuRIIAJn1ilXtI7fkuCvqJRtgOjt6Ncallback=Geolocation.build:32 Google Maps API error: InvalidKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#invalid-key-map-error"

**Comment by lekkerduidelijk** [comment]
I've created a fix for the API key. Now you can add your API key in the [geolocation.js](https://github.com/lekkerduidelijk/kirby-geolocation-field/blob/master/assets/js/geolocation.js#L152) file and get the plugin working again.

I have some doubts about where this setting should be set but this will do for now.
While I was at it I fixed JSHint issues and decreased the default zoom level.

@CodeStalker @maximiliankiepe Can you check it out?

**Comment by CodeStalker** [comment]
OK the plugin now works, but i have another odd issue. Its not out putting the numbers! Im my mardown content file, the plugin is generating this:

Location: sdfsdf,sdfsf

Weird!

Any ideas?

**Comment by CodeStalker** [comment]
Ok, i think it was becuase i was working with an article that was created with the previous version of the plugin. It works fine if I create a new page.

**Comment by maximiliankiepe** [comment]
works perfectly, nice work !

**Comment by lekkerduidelijk** [comment]
@maximiliankiepe Happy to help!
